# Generated by Django 3.1.1 on 2020-12-13 07:17

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_product_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bldgroom',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cust_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pickup_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=crm.models.get_image_path),
        ),
    ]
