# Generated by Django 3.1.1 on 2020-12-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20201213_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='charge',
            new_name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default=1, upload_to='products/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
